options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ===== BACKEND BUILD =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/catalyst-backend:latest',
        '-f', 'Dockerfile.backend',
        '.'
      ]

  # ===== FRONTEND BUILD =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/catalyst-frontend:latest',
        '-f', 'Dockerfile.frontend',  # FIXED: Use frontend-specific file
        '.'
      ]

  # ===== PUSH IMAGES =====
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-frontend:latest']

  # ===== DEPLOY BACKEND =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy catalyst-backend \
          --image gcr.io/$PROJECT_ID/catalyst-backend:latest \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets="DB_HOST=db-connection-name:latest,DB_USER=db-user:latest,DB_PASS=db-password:latest,FIREBASE_CONFIG=firebase-config:latest" \
          --set-env-vars "DB_PORT=3306,DB_NAME=catalystdb,GCS_BUCKET_NAME=catalyst-cloud-storage" \
          --timeout=300s \
          --cpu=1 \
          --memory=512Mi

  # ===== DEPLOY FRONTEND =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy catalyst-frontend \
          --image gcr.io/$PROJECT_ID/catalyst-frontend:latest \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated \
          --memory=256Mi \
          --cpu=1

images:
  - 'gcr.io/$PROJECT_ID/catalyst-backend:latest'
  - 'gcr.io/$PROJECT_ID/catalyst-frontend:latest'