steps:
  # Build the Kobweb application
  - name: 'gradle:8.8-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y curl && \
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
        apt-get install -y nodejs && \
        gradle :site:build --no-daemon

  # Build Docker image with nginx
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA',
      '-f', 'Dockerfile.runtime',
      '.'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'catalyst-page',
      '--image', 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA'