options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ===== BACKEND BUILD =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA',
        '-f', 'Dockerfile.backend',
        '.'
      ]

  # ===== FRONTEND BUILD =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA',
        '-f', 'Dockerfile.frontend',
        '.'
      ]

  # ===== PUSH IMAGES =====
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA']

  # ===== DEPLOY BACKEND =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'catalyst-backend'
      - '--image=gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'

  # ===== DEPLOY FRONTEND =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'catalyst-frontend'
      - '--image=gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'

images:
  - 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA'