options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --- BACKEND BUILD ---
  - name: 'gradle:8.8-jdk17'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x ./gradlew
        ./gradlew :site:jvmJar --no-daemon

  # Build Backend Docker image - THIS WAS MISSING
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    waitFor: ['build-backend']
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA',
      '-f', 'Dockerfile.backend',  # Make sure this has the .env file creation
      '.'
    ]

  # --- FRONTEND BUILD ---
  - name: 'gradle:8.8-jdk17'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y curl && \
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
        apt-get install -y nodejs && \
        chmod +x ./gradlew && \
        ./gradlew :site:build --no-daemon

  # Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    waitFor: ['build-frontend']
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA',
      '-f', 'Dockerfile.frontend',
      '.'
    ]

  # --- PUSH IMAGES ---
  # Push Backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    waitFor: ['build-backend-image']
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA']

  # Push Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    waitFor: ['build-frontend-image']
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA']

  # --- DEPLOY SERVICES ---
  # Deploy Backend - USE THE CORRECT ENVIRONMENT VARIABLES
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    waitFor: ['push-backend']
    args: [
      'run', 'deploy', 'catalyst-backend',
      '--image', 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--set-env-vars', 'DB_HOST=your-actual-db-host,DB_PORT=3306,DB_NAME=your-actual-db-name,DB_USER=your-actual-db-user,DB_PASS=your-actual-db-password,GCS_BUCKET_NAME=your-actual-bucket,GCS_CREDENTIALS_PATH=,FIREBASE_API_KEY=your-firebase-key,FIREBASE_AUTH_DOMAIN=your-domain,FIREBASE_PROJECT_ID=your-project-id,FIREBASE_STORAGE_BUCKET=your-bucket,FIREBASE_MESSAGING_SENDER_ID=your-sender-id,FIREBASE_APP_ID=your-app-id'
    ]

  # Deploy Frontend
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']
    args: [
      'run', 'deploy', 'catalyst-frontend',
      '--image', 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

images:
  - 'gcr.io/$PROJECT_ID/catalyst-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/catalyst-frontend:$COMMIT_SHA'