options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Kobweb application
  - name: 'gradle:8.8-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y curl && \
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
        apt-get install -y nodejs && \
        gradle :site:build --no-daemon

  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA',
      '-f', 'Dockerfile.runtime',
      '.'
    ]

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'catalyst-page',
      '--image', 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'  # ← ADD THIS LINE
    ]

images:
  - 'gcr.io/$PROJECT_ID/catalyst-page:$COMMIT_SHA'