options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --- BUILD UNIFIED KOBWEB APPLICATION ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app-image'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/catalyst-app:$COMMIT_SHA',
      '-f', 'Dockerfile.backend',  # This will build the complete Kobweb app
      '.'
    ]

  # --- PUSH IMAGE ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-app'
    waitFor: ['build-app-image']
    args: ['push', 'gcr.io/$PROJECT_ID/catalyst-app:$COMMIT_SHA']

  # --- DEPLOY SINGLE APPLICATION ---
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    waitFor: ['push-app']
    args: [
      'run', 'deploy', 'catalyst-app',
      '--image', 'gcr.io/$PROJECT_ID/catalyst-app:$COMMIT_SHA',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--set-env-vars',
      'DB_HOST=sm://$PROJECT_ID/db-connection-name,DB_PORT=3306,DB_NAME=catalystdb,DB_USER=sm://$PROJECT_ID/db-user,DB_PASS=sm://$PROJECT_ID/db-password,GCS_BUCKET_NAME=catalyst-cloud-storage,GCS_CREDENTIALS_PATH=,FIREBASE_CONFIG=sm://$PROJECT_ID/firebase-config',
      '--add-cloudsql-instances', '$PROJECT_ID:asia-southeast1:catalyst-db'
    ]

images:
  - 'gcr.io/$PROJECT_ID/catalyst-app:$COMMIT_SHA'